In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# load the collected datapoints json files for each pose
df_downwarddog = pd.read_json('yoga-dataset/collected-datapoints/downwarddog_data.json')
df_mountain = pd.read_json('yoga-dataset/collected-datapoints/mountain_data.json')
df_tree = pd.read_json('yoga-dataset/collected-datapoints/tree_data.json')
# df_warrior1 = pd.read_json('yoga-dataset/collected-datapoints/warrior1_data.json')
df_warrior2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2_data.json')

# loading additional collected data
df_downwarddog_2 = pd.read_json('yoga-dataset/collected-datapoints/downwarddog-2_data.json')
df_warrior2_2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2-2_data.json')
df_tree_2 = pd.read_json('yoga-dataset/collected-datapoints/tree-2_data.json')
df_goddess = pd.read_json('yoga-dataset/collected-datapoints/goddess_data.json')

In [3]:
df_downwarddog
# downwarddog_list = []
# for i in range(0,len(dfs)):
#     downwarddog_list.append('Downward Dog')


0           1           2           3           4           5   \
0    37.320096  295.286053  -23.097323  284.030125  264.544473  401.922498   
1   319.524752  239.445449  301.375813  280.339137  314.601509  187.211990   
2   635.553449  223.751653  -20.470403  643.599906  247.634287  394.652199   
3   537.640177  282.698466  356.379955  532.447752  327.199242  177.452749   
4   288.360819  356.084288  -20.381945  408.632850  -12.923662  391.973682   
5   134.550553   77.159201  356.914822  136.380658  171.837894  175.015978   
6   291.000369  354.656113  310.087321  358.348811  332.151135  404.275558   
7   162.335143   84.778089  214.844757  131.006125  130.298023  175.272393   
8   287.806933  388.905148  387.291198  392.792551  359.859671  378.182682   
9   133.936364  136.982422  244.863167  121.037151  171.431443  159.517248   
10  268.926655  331.391127  311.340076  349.037991  313.614820  298.883337   
11  164.683301   95.676146  231.440088  164.024786  170.155870   34.987118   
12  301.812340  356.290088  -23.680166  407.331400  362.383230  338.478728   
13  140.954523  113.163265  360.944226  143.128173  178.568481   65.223327   
14  252.937591  379.542384  339.253481  406.756407  328.492294  298.290959   
15  143.119604   80.419333  228.058351  143.583680  165.956423   24.437356   
16  245.830363  373.995547  346.695191  397.062485  335.473766  306.379252   
17  133.123556   77.643549  230.881243  140.960489  169.001778   36.523798   
18  467.948079  197.338430  353.020352  165.657546  238.300610  132.350419   
19  308.791456  302.907344  249.243829  308.475423  290.095984  195.181899   
20  480.838552  188.923653  355.335603  173.943926  244.963160  131.682490   
21  310.485127  294.723257  240.532854  306.853721  288.802400  196.804912   
22  275.172988  307.375992  298.846269  545.684696  357.872272  319.970855   
23  184.137376  117.243852  264.421928  507.882151  214.934035   95.617932   
24   49.146391  315.522214  384.969297  563.471243  359.769919  323.614877   
25  512.685395  114.773700  262.258367  508.355499  212.558784   82.636738   
26  248.167919  368.067432  339.136103  390.402861  340.785734  299.368103   
27  132.651804   88.688233  243.612825  146.470012  174.621706   20.203986   
28  241.194940  479.274304  339.842040  397.800948  339.674884  306.305041   
29  133.189674  195.352512  244.392213  145.051830  175.513740   22.544078   
30   64.202487  587.830131  318.406512  592.734223  464.082715  132.449671   
31  337.985051  301.601069  261.828756  330.523354  338.228090  211.564305   
32   64.279785  180.989824  319.746930  586.470924  459.439066  126.068861   
33  336.716698  300.660453  260.682758  332.648802  337.923114  204.291745   

            6           7           8           9   ...          80  \
0   -22.132131  348.299869  186.100932  231.928331  ...  387.778833   
1   231.298486  367.882569  308.619209  309.302081  ...  329.399813   
2   -10.315262  372.512540   20.154801  184.394398  ...  363.175196   
3   227.383040  370.700123  350.855765  291.207974  ...  300.355818   
4   186.615679  357.359785   10.599844  231.939465  ...  289.001740   
5   401.477193  381.455002  360.472664  293.876003  ...  260.589205   
6    -2.202779  375.275261  445.116010  346.988008  ...  423.250357   
7   231.492317  369.567083  291.867362  208.296886  ...  332.203155   
8   564.312834  333.850392  285.969837  341.699181  ...  368.881019   
9   -80.066276  362.050211  245.670408  251.137068  ...  290.422734   
10  380.944644  262.394611  267.487403  356.884728  ...  289.110131   
11  279.796176  286.057461  189.207654  198.690836  ...  265.091842   
12  387.176898  285.169834  305.924353  404.861191  ...  389.789298   
13  282.979314  281.956203  171.141324  178.948846  ...  298.545340   
14  388.320275  261.703608  396.691999  357.604078  ...  288.232707   
15  252.004499  265.174527  239.605347  169.959323  ...  244.809969   
16  386.808959  250.729952  280.668831  365.500821  ...  304.619027   
17 

In [4]:
# df_downwarddog_2

In [5]:
# df_mountain

In [6]:
# df_tree

In [7]:
# df_tree_2

In [8]:
# df_goddess

In [9]:
# df_warrior2

In [10]:
# df_warrior2_2

In [11]:
# transpose the dataframes, then concat and then change the labels on the rows
dfs = [df_downwarddog, df_downwarddog_2, df_mountain, df_tree, df_tree_2, df_goddess, df_warrior2, df_warrior2_2]
idx = 0;
for i in range(len(dfs)):
    dfs[i] = dfs[i].transpose()
    idx += len(dfs[i])

In [12]:
# of data
idx

985

In [13]:
rows_list = []
for i in range(0, idx):
    rows_list.append(i)

In [14]:
# rows_list

In [15]:
yoga_df = pd.concat(dfs)

In [16]:
yoga_df

0           1           2           3           4           5   \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
175  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
176  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
177  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
178  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
179  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

             6           7           8           9   ...          24  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
175  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
176  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
177  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
178  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
179  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

             25          26          27          28          29          30  \
0    512.685395  248.167919  132.651804  241.194940  133.189674   64.202487   
1    114.773700  368.067432   88.688233  479.274304  195.352512  587.830131   
2    262.258367  339.136103  243.612825  339.842040  244.392213  318.406512   
3    508.355499  390.402861  146.470012  397.800948  145.051830  592.734223   
4    212.558784  340.785734  174.621706  339.674884  175.513740  464.082715   
..          ...         ...         ...         ...         ...         ...   
175  308.603516  317.078634  337.504294  323.198185  340.634462  362.919048   
176  265.650801  210.158264  307.353250  190.137878  303.216576  178.155038   
177  357.821316  247.814875  375.504241  248.505517  378.786821  265.659332   
178  274.419306  229.593891  330.896006  234.878177  333.630077  246.321285   
179  302.332540  249.802959  377.591386  454.740128  331.544983  437.429437   

             31          32          33  
0    337.985051   64.279785  336.716698  
1    301.601069  180.989824  300.660453  
2    261.828756  319.746930  260.682758  
3    330.523354  586.470924  332.648802  
4    338.228090  459.439066  337.923114  
..          ...         ...         ...  
175  387.275087  368.603858  387.555554  
176  414.401903  178.609994  423.984033  
177  390.824568  246.407618  374.380358  
178  414.661471  246.809681  413.450458  
179  422.083878  435.417224  424.428084  

[985 rows x 34 columns]

In [17]:
class_names = ['downward dog', 'mountain', 'tree', 'goddess', 'warrior2']
pose_list = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    pose_list.append('Downward Dog')
for i in range(0,len(dfs[2])):
    pose_list.append('Mountain')
for i in range(0,len(dfs[3])+len(dfs[4])):
    pose_list.append('Tree')
for i in range(0,len(dfs[5])):
    pose_list.append('Goddess')
for i in range(0,len(dfs[6])+len(dfs[7])):
    pose_list.append('Warrior2')
    
#yoga_df['Pose'] = pose_list
save_df = yoga_df.copy()
save_df['Pose'] = pose_list
save_df.index = rows_list
save_df = save_df.transpose()
save_df
save_df.to_json("data.json")

In [18]:
labels = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    labels.append(0)
for i in range(0,len(dfs[2])):
    labels.append(1)
for i in range(0,len(dfs[3])+len(dfs[4])):
    labels.append(2)
for i in range(0,len(dfs[5])):
    labels.append(3)
for i in range(0,len(dfs[6])+len(dfs[7])):
    labels.append(4)

In [19]:
labels = np.array(labels)

In [20]:
type(labels)

numpy.ndarray

In [21]:
len(labels)

985

In [22]:
# change the rows so that the poses have pose starting from pose0 -> ...
yoga_df.index = rows_list

In [23]:
yoga_df

0           1           2           3           4           5   \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
980  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
981  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
982  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
983  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
984  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

             6           7           8           9   ...          24  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
980  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
981  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
982  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
983  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
984  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

             25          26          27          28          29          30  \
0    512.685395  248.167919  132.651804  241.194940  133.189674   64.202487   
1    114.773700  368.067432   88.688233  479.274304  195.352512  587.830131   
2    262.258367  339.136103  243.612825  339.842040  244.392213  318.406512   
3    508.355499  390.402861  146.470012  397.800948  145.051830  592.734223   
4    212.558784  340.785734  174.621706  339.674884  175.513740  464.082715   
..          ...         ...         ...         ...         ...         ...   
980  308.603516  317.078634  337.504294  323.198185  340.634462  362.919048   
981  265.650801  210.158264  307.353250  190.137878  303.216576  178.155038   
982  357.821316  247.814875  375.504241  248.505517  378.786821  265.659332   
983  274.419306  229.593891  330.896006  234.878177  333.630077  246.321285   
984  302.332540  249.802959  377.591386  454.740128  331.544983  437.429437   

             31          32          33  
0    337.985051   64.279785  336.716698  
1    301.601069  180.989824  300.660453  
2    261.828756  319.746930  260.682758  
3    330.523354  586.470924  332.648802  
4    338.228090  459.439066  337.923114  
..          ...         ...         ...  
980  387.275087  368.603858  387.555554  
981  414.401903  178.609994  423.984033  
982  390.824568  246.407618  374.380358  
983  414.661471  246.809681  413.450458  
984  422.083878  435.417224  424.428084  

[985 rows x 34 columns]

In [24]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [25]:
# add better labels to the columns for joint part
col_list = ['nose_x', 'nose_y', 'leftEye_x', 'leftEye_y', 'rightEye_x', 'rightEye_y', 'leftEar_x', 'leftEar_y', 
            'rightEar_x', 'rightEar_y', 'leftShoulder_x', 'leftShoulder_y', 'rightShoulder_x', 'rightShoulder_y', 
            'leftElbow_x', 'leftElbow_y', 'rightElbow_x', 'rightElbow_y', 'leftWrist_x', 'leftWrist_y', 
            'rightWrist_x', 'rightWrist_y', 'leftHip_x', 'leftHip_y', 'rightHip_x', 'rightHip_y', 'leftKnee_x', 
            'leftKnee_y', 'rightKnee_x', 'rightKnee_y', 'leftAnkle_x', 'leftAnkle_y', 'rightAnkle_x', 'rightAnkle_y']
print(len(col_list))

34


In [26]:
yoga_df.columns = col_list

In [27]:
yoga_df

nose_x      nose_y   leftEye_x   leftEye_y  rightEye_x  rightEye_y  \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
980  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
981  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
982  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
983  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
984  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

      leftEar_x   leftEar_y  rightEar_x  rightEar_y  ...  rightHip_x  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
980  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
981  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
982  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
983  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
984  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

     rightHip_y  leftKnee_x  leftKnee_y  rightKnee_x  rightKnee_y  \
0    512.685395  248.167919  132.651804   241.194940   133.189674   
1    114.773700  368.067432   88.688233   479.274304   195.352512   
2    262.258367  339.136103  243.612825   339.842040   244.392213   
3    508.355499  390.402861  146.470012   397.800948   145.051830   
4    212.558784  340.785734  174.621706   339.674884   175.513740   
..          ...         ...         ...          ...          ...   
980  308.603516  317.078634  337.504294   323.198185   340.634462   
981  265.650801  210.158264  307.353250   190.137878   303.216576   
982  357.821316  247.814875  375.504241   248.505517   378.786821   
983  274.419306  229.593891  330.896006   234.878177   333.630077   
984  302.332540  249.802959  377.591386   454.740128   331.544983   

     leftAnkle_x  leftAnkle_y  rightAnkle_x  rightAnkle_y  
0      64.202487   337.985051     64.279785    336.716698  
1     587.830131   301.601069    180.989824    300.660453  
2     318.406512   261.828756    319.746930    260.682758  
3     592.734223   330.523354    586.470924    332.648802  
4     464.082715   338.228090    459.439066    337.923114  
..           ...          ...           ...           ...  
980   362.919048   387.275087    368.603858    387.555554  
981   178.155038   414.401903    178.609994    423.984033  
982   265.659332   390.824568    246.407618    374.380358  
983   246.321285   414.661471    246.809681    413.450458  
984   437.429437   422.083878    435.417224    424.428084  

[985 rows x 34 columns]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
features_train, features_test, labels_train, labels_test = train_test_split(yoga_df, labels, test_size=0.35, random_state=42)

In [30]:
# scale the data
from sklearn.preprocessing import MinMaxScaler

In [31]:
scaler = MinMaxScaler()

In [32]:
scaler.fit(features_train)

MinMaxScaler()

In [33]:
features_train = scaler.transform(features_train)

In [34]:
features_test = scaler.transform(features_test)

In [35]:
features_train

array([[0.45233687, 0.56731988, 0.46087208, ..., 0.56833417, 0.27543326,
        0.57336294],
       [0.58931351, 0.86958483, 0.57006109, ..., 0.66630264, 0.18224281,
        0.67526393],
       [0.51261747, 0.35848335, 0.51224471, ..., 0.67843779, 0.49158378,
        0.68312599],
       ...,
       [0.3350187 , 0.42544165, 0.32610543, ..., 0.21153753, 0.28712303,
        0.22662454],
       [0.47605525, 0.46705041, 0.47180857, ..., 0.67511073, 0.48486071,
        0.67889035],
       [0.71040863, 0.91643517, 0.03706213, ..., 0.58032143, 0.21409719,
        0.60483283]])

In [36]:
features_test

array([[0.52200066, 0.48569984, 0.52806841, ..., 0.74311251, 0.51495632,
        0.75098482],
       [0.49793386, 0.33260912, 0.50453954, ..., 0.62602743, 0.48911282,
        0.63400011],
       [0.51546587, 0.58227963, 0.51545278, ..., 0.60953476, 0.36618314,
        0.62512698],
       ...,
       [0.50417069, 0.38834337, 0.50849248, ..., 0.664389  , 0.37370608,
        0.64905768],
       [0.64209862, 0.71073088, 0.68498938, ..., 0.45950835, 0.1800482 ,
        0.50587218],
       [0.51096761, 0.44595581, 0.51788907, ..., 0.6773274 , 0.46412081,
        0.6909293 ]])

In [37]:
labels_train

array([4, 0, 2, 0, 0, 4, 0, 4, 3, 0, 3, 0, 0, 0, 3, 3, 0, 4, 4, 0, 0, 4,
       0, 0, 2, 2, 0, 4, 2, 0, 0, 2, 0, 2, 0, 1, 2, 4, 4, 0, 2, 4, 3, 3,
       4, 1, 0, 3, 4, 4, 3, 1, 2, 3, 2, 2, 2, 0, 3, 2, 4, 3, 1, 0, 0, 2,
       1, 1, 1, 1, 3, 1, 0, 0, 1, 2, 3, 0, 4, 4, 4, 2, 2, 2, 0, 3, 4, 2,
       2, 4, 0, 0, 3, 4, 4, 1, 1, 0, 0, 3, 4, 1, 0, 0, 1, 4, 1, 0, 2, 0,
       1, 4, 4, 4, 2, 4, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 4, 2, 3, 0, 2, 0,
       2, 1, 3, 4, 3, 0, 1, 3, 4, 4, 3, 1, 4, 0, 2, 1, 2, 0, 0, 4, 4, 0,
       2, 4, 3, 2, 1, 0, 0, 1, 4, 1, 2, 0, 0, 0, 1, 4, 4, 1, 2, 2, 4, 0,
       3, 0, 2, 0, 4, 1, 4, 2, 0, 0, 3, 2, 0, 1, 0, 2, 0, 4, 2, 2, 2, 0,
       0, 2, 3, 0, 3, 4, 1, 1, 0, 1, 0, 4, 4, 4, 1, 2, 3, 1, 1, 4, 0, 0,
       4, 0, 1, 4, 0, 2, 1, 2, 1, 0, 4, 4, 4, 1, 2, 3, 0, 0, 0, 4, 4, 3,
       4, 0, 1, 2, 2, 3, 0, 0, 1, 0, 3, 4, 0, 0, 3, 0, 1, 4, 3, 3, 4, 3,
       2, 4, 0, 4, 0, 4, 0, 0, 2, 0, 4, 4, 2, 3, 2, 1, 3, 4, 0, 0, 4, 2,
       4, 1, 0, 0, 4, 1, 2, 4, 4, 3, 3, 0, 4, 4, 2,

In [38]:
features_train.shape

(640, 34)

In [39]:
features_test.shape

(345, 34)

In [40]:
# do KNN model here and see results
from sklearn.neighbors import KNeighborsClassifier

In [41]:
classifier = KNeighborsClassifier(n_neighbors=15)

In [42]:
classifier.fit(features_train, labels_train)

KNeighborsClassifier(n_neighbors=15)

In [43]:
pred = classifier.predict(features_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [45]:
# confusion matrix
print(confusion_matrix(labels_test, pred))

[[81  0  0  3  3]
 [ 0 50 12  0  1]
 [ 0  2 73  3  5]
 [ 0  2  8 16 11]
 [ 0  3 20  9 43]]


In [46]:
# classification report
print(classification_report(labels_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        87
           1       0.88      0.79      0.83        63
           2       0.65      0.88      0.74        83
           3       0.52      0.43      0.47        37
           4       0.68      0.57      0.62        75

    accuracy                           0.76       345
   macro avg       0.74      0.72      0.73       345
weighted avg       0.77      0.76      0.76       345



In [47]:
# accuracy_score
print(accuracy_score(labels_test, pred))

0.7623188405797101


In [48]:
# import tensorflow as tf

In [49]:
# print(tf.__version__)

In [50]:
# see results of tensorflow model
# from tensorflow.keras.layers import Input, Dense, Activation, Dropout
# from tensorflow.keras.models import Model

In [51]:
# yoga_df.shape[1]

In [52]:
# input_layer = Input(shape=(yoga_df.shape[1],))

In [53]:
# dense_layer_1 = Dense(15, activation='relu')(input_layer)

In [54]:
# dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)

In [55]:
# output = Dense(5, activation='softmax')(dense_layer_2)

In [56]:
# model = Model(inputs=input_layer, outputs=output)

In [57]:
# model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [58]:
# print(model.summary())

In [59]:
# history = model.fit(features_train,labels_train, batch_size=8,epochs=50,verbose=1,validation_split=0.35)

In [60]:
# score = model.evaluate(features_test, labels_test, verbose=1)

In [61]:
# print("test score: ",  score[0])

In [62]:
# print("test accuracy: ", score[1])