In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
# load the collected datapoints json files for each pose
df_downwarddog = pd.read_json('yoga-dataset/collected-datapoints/downwarddog_data.json')
df_mountain = pd.read_json('yoga-dataset/collected-datapoints/mountain_data.json')
df_tree = pd.read_json('yoga-dataset/collected-datapoints/tree_data.json')
# df_warrior1 = pd.read_json('yoga-dataset/collected-datapoints/warrior1_data.json')
df_warrior2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2_data.json')

# loading additional collected data
df_downwarddog_2 = pd.read_json('yoga-dataset/collected-datapoints/downwarddog-2_data.json')
df_warrior2_2 = pd.read_json('yoga-dataset/collected-datapoints/warrior2-2_data.json')
df_tree_2 = pd.read_json('yoga-dataset/collected-datapoints/tree-2_data.json')
df_goddess = pd.read_json('yoga-dataset/collected-datapoints/goddess_data.json')

In [4]:
df_downwarddog
# downwarddog_list = []
# for i in range(0,len(dfs)):
#     downwarddog_list.append('Downward Dog')


0           1           2           3           4           5   \
0    37.320096  295.286053  -23.097323  284.030125  264.544473  401.922498   
1   319.524752  239.445449  301.375813  280.339137  314.601509  187.211990   
2   635.553449  223.751653  -20.470403  643.599906  247.634287  394.652199   
3   537.640177  282.698466  356.379955  532.447752  327.199242  177.452749   
4   288.360819  356.084288  -20.381945  408.632850  -12.923662  391.973682   
5   134.550553   77.159201  356.914822  136.380658  171.837894  175.015978   
6   291.000369  354.656113  310.087321  358.348811  332.151135  404.275558   
7   162.335143   84.778089  214.844757  131.006125  130.298023  175.272393   
8   287.806933  388.905148  387.291198  392.792551  359.859671  378.182682   
9   133.936364  136.982422  244.863167  121.037151  171.431443  159.517248   
10  268.926655  331.391127  311.340076  349.037991  313.614820  298.883337   
11  164.683301   95.676146  231.440088  164.024786  170.155870   34.987118   
12  301.812340  356.290088  -23.680166  407.331400  362.383230  338.478728   
13  140.954523  113.163265  360.944226  143.128173  178.568481   65.223327   
14  252.937591  379.542384  339.253481  406.756407  328.492294  298.290959   
15  143.119604   80.419333  228.058351  143.583680  165.956423   24.437356   
16  245.830363  373.995547  346.695191  397.062485  335.473766  306.379252   
17  133.123556   77.643549  230.881243  140.960489  169.001778   36.523798   
18  467.948079  197.338430  353.020352  165.657546  238.300610  132.350419   
19  308.791456  302.907344  249.243829  308.475423  290.095984  195.181899   
20  480.838552  188.923653  355.335603  173.943926  244.963160  131.682490   
21  310.485127  294.723257  240.532854  306.853721  288.802400  196.804912   
22  275.172988  307.375992  298.846269  545.684696  357.872272  319.970855   
23  184.137376  117.243852  264.421928  507.882151  214.934035   95.617932   
24   49.146391  315.522214  384.969297  563.471243  359.769919  323.614877   
25  512.685395  114.773700  262.258367  508.355499  212.558784   82.636738   
26  248.167919  368.067432  339.136103  390.402861  340.785734  299.368103   
27  132.651804   88.688233  243.612825  146.470012  174.621706   20.203986   
28  241.194940  479.274304  339.842040  397.800948  339.674884  306.305041   
29  133.189674  195.352512  244.392213  145.051830  175.513740   22.544078   
30   64.202487  587.830131  318.406512  592.734223  464.082715  132.449671   
31  337.985051  301.601069  261.828756  330.523354  338.228090  211.564305   
32   64.279785  180.989824  319.746930  586.470924  459.439066  126.068861   
33  336.716698  300.660453  260.682758  332.648802  337.923114  204.291745   

            6           7           8           9   ...          80  \
0   -22.132131  348.299869  186.100932  231.928331  ...  387.778833   
1   231.298486  367.882569  308.619209  309.302081  ...  329.399813   
2   -10.315262  372.512540   20.154801  184.394398  ...  363.175196   
3   227.383040  370.700123  350.855765  291.207974  ...  300.355818   
4   186.615679  357.359785   10.599844  231.939465  ...  289.001740   
5   401.477193  381.455002  360.472664  293.876003  ...  260.589205   
6    -2.202779  375.275261  445.116010  346.988008  ...  423.250357   
7   231.492317  369.567083  291.867362  208.296886  ...  332.203155   
8   564.312834  333.850392  285.969837  341.699181  ...  368.881019   
9   -80.066276  362.050211  245.670408  251.137068  ...  290.422734   
10  380.944644  262.394611  267.487403  356.884728  ...  289.110131   
11  279.796176  286.057461  189.207654  198.690836  ...  265.091842   
12  387.176898  285.169834  305.924353  404.861191  ...  389.789298   
13  282.979314  281.956203  171.141324  178.948846  ...  298.545340   
14  388.320275  261.703608  396.691999  357.604078  ...  288.232707   
15  252.004499  265.174527  239.605347  169.959323  ...  244.809969   
16  386.808959  250.729952  280.668831  365.500821  ...  304.619027   
17 

In [5]:
df_downwarddog_2

0           1           2           3           4           5    \
0   285.515735  240.262513  449.021424  413.325936  378.084380  375.440099   
1   304.564765  281.277131  238.663078  245.847329  227.700404  157.640063   
2   272.672779  238.532781  306.591265  418.126064  367.412717  372.822000   
3   297.327753  272.503952  245.077099  245.853105  220.856183  139.526937   
4   290.150170  225.942079  469.719571  406.737635  376.545895  366.466288   
5   266.214319  282.937629  246.093218  246.413090  217.814742  145.950685   
6   268.244999  199.280251  395.868875  387.741861  355.552005  356.966272   
7   292.947813  286.657458   91.473032  255.872978  215.019360  138.828011   
8   271.660118  213.374289  506.231989  405.941148  368.636612  357.034898   
9   285.957867  297.231844   53.548665  247.188450  211.100742  139.287622   
10  372.651006  274.638881  392.207183  314.672928  349.953338  341.648035   
11   70.337959  285.284989   86.115162  167.249932  234.612814  127.193143   
12  369.701977  215.670370  453.146621  401.095308  372.707890  372.091896   
13   72.579445  342.761962   82.015044  259.900178  229.406786  101.267669   
14  396.262350  266.467846  463.295195  245.126345  371.860523  350.955663   
15   42.639920  282.387068  265.942554  266.908895  293.401439   85.542771   
16  399.743434  192.182465  325.174375  370.111298  395.043584  356.886134   
17   50.435520  364.766993  199.717728  179.169656  298.846250   91.898122   
18  294.144786  118.913546  231.855735  478.320047  235.577806  312.213472   
19  234.684973  413.435410  266.574204  407.485599  411.038310  162.269881   
20  292.570525  106.039963  235.278434  475.934308  236.311976  217.055721   
21  253.643338  419.755859  263.522769  406.256004  406.562272  238.945047   
22  297.142871  409.472846  459.453923  139.368122  311.291893  319.936466   
23  203.654966  164.554771  111.378986  392.554110  270.877272  166.556135   
24  299.814795  481.901105  430.429194   87.873127  317.019242  325.861655   
25  202.474332  355.921351  120.299504  411.685235  268.555979  164.701293   
26  402.880973  399.951058  462.146728  382.849625  292.979580  353.741070   
27   54.252398   86.365041  265.356692  236.987115  330.100012   86.553950   
28  400.463772  392.900467  455.720908  378.697980  402.452806  349.558723   
29   54.757750   85.909552  264.362004  236.299265  298.419679   87.927427   
30  574.218598  562.129666  582.151363  188.407196  445.000152  525.342405   
31  379.692630  392.199052  364.698482  411.597117  402.037558  320.222785   
32  559.764143  558.846782  577.726395  198.111815  446.104580  512.393110   
33  372.400368  389.033089  362.779631  403.782299  399.404411  314.132607   

           6           7           8           9    ...         162  \
0   337.929194  267.766047  268.669500  206.111799  ...  421.086454   
1   192.020059  295.759933  297.176974  315.893612  ...  254.118700   
2   344.675834  271.028412  250.837849  204.665727  ...  415.541099   
3   187.501748  285.699135  295.584266  309.337343  ...  248.597740   
4   342.158051  388.810494  250.865227  198.633306  ...  398.848492   
5   189.799672  186.974214  292.155771  311.809681  ...  212.959269   
6   368.590672  364.089897  274.110150  192.492172  ...  384.500395   
7   143.390344   95.832415  317.233174  311.444971  ...  211.307036   
8   331.941041  393.566467  240.121367  194.700818  ...  391.704273   
9   185.579098  134.787208  321.285377  313.173258  ...  213.592838   
10  382.396758  348.628329  382.238418  238.871310  ...  299.843104   
11  128.756403  178.737916  100.359257  329.792072  ...  115.499092   
12  397.725673  350.325458  419.235279  215.716937  ...  375.518148   
13  119.868734  182.736484   95.531790  355.064902  ...  181.737179   
14  388.307583  320.121633  390.831256  312.622602  ...  359.364892   
15  136.488251  189.583441   85.560079  241.014447  ...  185.196984   
16  330.908735  321.254142  386.989148  499.744042  ...  349.459471   
17

In [6]:
df_mountain

0           1           2           3           4           5    \
0   319.050720  333.910810  312.053726  331.786615  326.611670  325.413120   
1    69.621763   66.929129   62.948810   64.005863   87.827680   39.021224   
2   331.091356  339.935402  319.257850  336.870212  333.950746  335.959843   
3    63.023734   61.280408   57.190103   55.586061   82.823406   33.477170   
4   310.827285  321.542513  301.273065  318.893254  315.609459  316.781619   
5    61.520664   62.486093   54.865960   57.643634   79.654365   30.819667   
6   350.296921  355.502303  330.343735  353.814940  349.366754  348.950366   
7    67.769191   71.236368   64.461390   64.575148   85.826886   44.135201   
8   292.998560  310.454824  286.556705  308.164974  299.191714  298.125304   
9    72.027669   66.439081   63.196247   63.573478   87.847535   41.980332   
10  365.146180  372.557112  351.495585  371.995379  360.439415  378.931519   
11  128.478766  113.343777  113.546461  115.375863  134.297635   94.134868   
12  270.387224  288.914249  266.384667  284.194925  276.313629  277.061497   
13  129.278997  115.070107  116.070286  112.044227  134.122690   96.182800   
14  384.304893  391.311482  369.380776  387.885077  380.055934  404.268338   
15  194.129092  173.107559  174.760362  176.672601  192.460235  166.374331   
16  248.488323  276.935418  253.161384  268.410426  254.823364  240.949356   
17  189.581313  174.649615  180.225388  178.484599  199.390218  156.906862   
18  410.935182  405.255920  391.489315  394.010518  404.707829  420.684126   
19  265.483949  220.150493  231.572342  236.502158  253.592724  218.304638   
20  216.655691  264.651705  238.598823  251.094187  232.293763  224.609280   
21  255.383709  230.536159  236.880073  233.107768  252.089426  225.123286   
22  343.211713  362.050971  347.478341  349.518786  342.986077  356.402298   
23  248.812280  233.749981  232.215106  234.704675  249.015876  227.645743   
24  286.125859  302.428677  285.456419  296.223857  298.335702  294.360371   
25  248.436246  230.748457  233.011650  234.780767  259.823383  235.126098   
26  335.307940  337.562204  337.794185  338.600400  337.837997  339.243753   
27  350.473196  323.865516  333.228470  330.542201  342.005715  332.443002   
28  296.705944  297.943063  290.724024  297.936622  307.417049  303.736587   
29  346.603918  324.811907  332.576757  331.857293  347.741823  338.365341   
30  329.482270  303.966573  339.975605  347.632995  340.205040  338.950974   
31  444.750388  411.082046  417.708992  417.015405  437.319431  440.475704   
32  301.639903  366.550036  295.915157  300.140614  309.814776  315.133527   
33  440.407534  410.538211  423.270762  427.089806  436.867210  442.159685   

           6           7           8           9    ...         150  \
0   317.925736  327.417543  304.980089  318.220927  ...  326.003807   
1    39.774032   51.813594   57.088143   51.620438  ...   83.138812   
2   328.068458  335.387129  312.929080  325.999058  ...  336.266833   
3    32.453718   40.962199   48.227169   41.103620  ...   76.041027   
4   307.270622  315.481670  293.687511  303.966174  ...  317.270622   
5    29.904956   39.508337   46.343286   39.989807  ...   72.494538   
6   344.104184  347.480925  324.226806  348.574941  ...  349.636240   
7    40.960841   52.268874   56.368574   49.314896  ...   84.116420   
8   289.658906  301.555242  274.252474  297.140914  ...  308.498127   
9    38.375895   50.279878   53.612502   51.603871  ...   81.910377   
10  370.980476  373.018414  351.410772  366.974290  ...  367.564636   
11   97.062561  112.605826  117.899612  112.631646  ...  124.267768   
12  261.194636  271.567687  249.988866  267.331628  ...  287.654046   
13   96.358505  110.590326  114.463746  114.274000  ...  128.709608   
14  394.952274  390.003572  381.779472  398.037869  ...  395.104610   
15  162.895071  179.878557  185.466869  176.445863  ...  180.067219   
16  233.643642  242.043619  221.868521  247.744844  ...  263.110105   
17

In [68]:
# df_tree

In [69]:
# df_tree_2

In [70]:
# df_goddess

In [71]:
# df_warrior2

In [72]:
# df_warrior2_2

In [73]:
# transpose the dataframes, then concat and then change the labels on the rows
dfs = [df_downwarddog, df_downwarddog_2, df_mountain, df_tree, df_tree_2, df_goddess, df_warrior2, df_warrior2_2]
idx = 0;
for i in range(len(dfs)):
    dfs[i] = dfs[i].transpose()
    idx += len(dfs[i])

In [74]:
# of data
idx

985

In [75]:
rows_list = []
for i in range(0, idx):
    rows_list.append(i)

In [76]:
# rows_list

In [77]:
yoga_df = pd.concat(dfs)

In [78]:
yoga_df

0           1           2           3           4           5   \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
175  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
176  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
177  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
178  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
179  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

             6           7           8           9   ...          24  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
175  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
176  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
177  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
178  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
179  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

             25          26          27          28          29          30  \
0    512.685395  248.167919  132.651804  241.194940  133.189674   64.202487   
1    114.773700  368.067432   88.688233  479.274304  195.352512  587.830131   
2    262.258367  339.136103  243.612825  339.842040  244.392213  318.406512   
3    508.355499  390.402861  146.470012  397.800948  145.051830  592.734223   
4    212.558784  340.785734  174.621706  339.674884  175.513740  464.082715   
..          ...         ...         ...         ...         ...         ...   
175  308.603516  317.078634  337.504294  323.198185  340.634462  362.919048   
176  265.650801  210.158264  307.353250  190.137878  303.216576  178.155038   
177  357.821316  247.814875  375.504241  248.505517  378.786821  265.659332   
178  274.419306  229.593891  330.896006  234.878177  333.630077  246.321285   
179  302.332540  249.802959  377.591386  454.740128  331.544983  437.429437   

             31          32          33  
0    337.985051   64.279785  336.716698  
1    301.601069  180.989824  300.660453  
2    261.828756  319.746930  260.682758  
3    330.523354  586.470924  332.648802  
4    338.228090  459.439066  337.923114  
..          ...         ...         ...  
175  387.275087  368.603858  387.555554  
176  414.401903  178.609994  423.984033  
177  390.824568  246.407618  374.380358  
178  414.661471  246.809681  413.450458  
179  422.083878  435.417224  424.428084  

[985 rows x 34 columns]

In [79]:
class_names = ['downward dog', 'mountain', 'tree', 'goddess', 'warrior2']
pose_list = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    pose_list.append('Downward Dog')
for i in range(0,len(dfs[2])):
    pose_list.append('Mountain')
for i in range(0,len(dfs[3])+len(dfs[4])):
    pose_list.append('Tree')
for i in range(0,len(dfs[5])):
    pose_list.append('Goddess')
for i in range(0,len(dfs[6])+len(dfs[7])):
    pose_list.append('Warrior2')
    
#yoga_df['Pose'] = pose_list
save_df = yoga_df.copy()
save_df['Pose'] = pose_list
save_df.index = rows_list
save_df = save_df.transpose()
save_df
save_df.to_json("data.json")

In [80]:
labels = []
for i in range(0,len(dfs[0])+len(dfs[1])):
    labels.append(0)
for i in range(0,len(dfs[2])):
    labels.append(1)
for i in range(0,len(dfs[3])+len(dfs[4])):
    labels.append(2)
for i in range(0,len(dfs[5])):
    labels.append(3)
for i in range(0,len(dfs[6])+len(dfs[7])):
    labels.append(4)

In [81]:
labels = np.array(labels)

In [82]:
type(labels)

numpy.ndarray

In [83]:
len(labels)

985

In [84]:
# change the rows so that the poses have pose starting from pose0 -> ...
yoga_df.index = rows_list

In [85]:
yoga_df

0           1           2           3           4           5   \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
980  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
981  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
982  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
983  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
984  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

             6           7           8           9   ...          24  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
980  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
981  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
982  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
983  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
984  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

             25          26          27          28          29          30  \
0    512.685395  248.167919  132.651804  241.194940  133.189674   64.202487   
1    114.773700  368.067432   88.688233  479.274304  195.352512  587.830131   
2    262.258367  339.136103  243.612825  339.842040  244.392213  318.406512   
3    508.355499  390.402861  146.470012  397.800948  145.051830  592.734223   
4    212.558784  340.785734  174.621706  339.674884  175.513740  464.082715   
..          ...         ...         ...         ...         ...         ...   
980  308.603516  317.078634  337.504294  323.198185  340.634462  362.919048   
981  265.650801  210.158264  307.353250  190.137878  303.216576  178.155038   
982  357.821316  247.814875  375.504241  248.505517  378.786821  265.659332   
983  274.419306  229.593891  330.896006  234.878177  333.630077  246.321285   
984  302.332540  249.802959  377.591386  454.740128  331.544983  437.429437   

             31          32          33  
0    337.985051   64.279785  336.716698  
1    301.601069  180.989824  300.660453  
2    261.828756  319.746930  260.682758  
3    330.523354  586.470924  332.648802  
4    338.228090  459.439066  337.923114  
..          ...         ...         ...  
980  387.275087  368.603858  387.555554  
981  414.401903  178.609994  423.984033  
982  390.824568  246.407618  374.380358  
983  414.661471  246.809681  413.450458  
984  422.083878  435.417224  424.428084  

[985 rows x 34 columns]

In [86]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [87]:
# add better labels to the columns for joint part
col_list = ['nose_x', 'nose_y', 'leftEye_x', 'leftEye_y', 'rightEye_x', 'rightEye_y', 'leftEar_x', 'leftEar_y', 
            'rightEar_x', 'rightEar_y', 'leftShoulder_x', 'leftShoulder_y', 'rightShoulder_x', 'rightShoulder_y', 
            'leftElbow_x', 'leftElbow_y', 'rightElbow_x', 'rightElbow_y', 'leftWrist_x', 'leftWrist_y', 
            'rightWrist_x', 'rightWrist_y', 'leftHip_x', 'leftHip_y', 'rightHip_x', 'rightHip_y', 'leftKnee_x', 
            'leftKnee_y', 'rightKnee_x', 'rightKnee_y', 'leftAnkle_x', 'leftAnkle_y', 'rightAnkle_x', 'rightAnkle_y']
print(len(col_list))

34


In [88]:
yoga_df.columns = col_list

In [89]:
yoga_df

nose_x      nose_y   leftEye_x   leftEye_y  rightEye_x  rightEye_y  \
0     37.320096  319.524752  635.553449  537.640177  288.360819  134.550553   
1    295.286053  239.445449  223.751653  282.698466  356.084288   77.159201   
2    -23.097323  301.375813  -20.470403  356.379955  -20.381945  356.914822   
3    284.030125  280.339137  643.599906  532.447752  408.632850  136.380658   
4    264.544473  314.601509  247.634287  327.199242  -12.923662  171.837894   
..          ...         ...         ...         ...         ...         ...   
980  264.289313  258.306253  268.597721  249.893718  264.735625  253.083734   
981  274.990785   85.454881  292.350780   73.905215  277.001136   71.958863   
982  212.949314  300.134287  217.132022  293.385366  215.704075  293.445214   
983  280.141583  138.403453  291.673874  133.374479  279.440661  127.957445   
984  357.377227  132.034252  260.143843  288.344936  350.846493  124.001835   

      leftEar_x   leftEar_y  rightEar_x  rightEar_y  ...  rightHip_x  \
0    291.000369  162.335143  287.806933  133.936364  ...   49.146391   
1    354.656113   84.778089  388.905148  136.982422  ...  315.522214   
2    310.087321  214.844757  387.291198  244.863167  ...  384.969297   
3    358.348811  131.006125  392.792551  121.037151  ...  563.471243   
4    332.151135  130.298023  359.859671  171.431443  ...  359.769919   
..          ...         ...         ...         ...  ...         ...   
980  276.321285  252.993829  265.775227  259.570464  ...  302.801290   
981  326.420575   83.796681  279.135457   84.049808  ...  293.494498   
982  218.867833  296.080641  225.327072  297.844191  ...  234.031569   
983  300.960318  130.099518  286.988426  134.390332  ...  311.395059   
984  328.221326  129.080131  344.641180  132.362027  ...  361.475749   

     rightHip_y  leftKnee_x  leftKnee_y  rightKnee_x  rightKnee_y  \
0    512.685395  248.167919  132.651804   241.194940   133.189674   
1    114.773700  368.067432   88.688233   479.274304   195.352512   
2    262.258367  339.136103  243.612825   339.842040   244.392213   
3    508.355499  390.402861  146.470012   397.800948   145.051830   
4    212.558784  340.785734  174.621706   339.674884   175.513740   
..          ...         ...         ...          ...          ...   
980  308.603516  317.078634  337.504294   323.198185   340.634462   
981  265.650801  210.158264  307.353250   190.137878   303.216576   
982  357.821316  247.814875  375.504241   248.505517   378.786821   
983  274.419306  229.593891  330.896006   234.878177   333.630077   
984  302.332540  249.802959  377.591386   454.740128   331.544983   

     leftAnkle_x  leftAnkle_y  rightAnkle_x  rightAnkle_y  
0      64.202487   337.985051     64.279785    336.716698  
1     587.830131   301.601069    180.989824    300.660453  
2     318.406512   261.828756    319.746930    260.682758  
3     592.734223   330.523354    586.470924    332.648802  
4     464.082715   338.228090    459.439066    337.923114  
..           ...          ...           ...           ...  
980   362.919048   387.275087    368.603858    387.555554  
981   178.155038   414.401903    178.609994    423.984033  
982   265.659332   390.824568    246.407618    374.380358  
983   246.321285   414.661471    246.809681    413.450458  
984   437.429437   422.083878    435.417224    424.428084  

[985 rows x 34 columns]

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
features_train, features_test, labels_train, labels_test = train_test_split(yoga_df, labels, test_size=0.35, random_state=42)

In [92]:
# scale the data
from sklearn.preprocessing import MinMaxScaler

In [93]:
scaler = MinMaxScaler()

In [94]:
scaler.fit(features_train)

MinMaxScaler()

In [95]:
features_train = scaler.transform(features_train)

In [96]:
features_test = scaler.transform(features_test)

In [97]:
features_train

array([[0.45233687, 0.56731988, 0.46087208, ..., 0.56833417, 0.27543326,
        0.57336294],
       [0.58931351, 0.86958483, 0.57006109, ..., 0.66630264, 0.18224281,
        0.67526393],
       [0.51261747, 0.35848335, 0.51224471, ..., 0.67843779, 0.49158378,
        0.68312599],
       ...,
       [0.3350187 , 0.42544165, 0.32610543, ..., 0.21153753, 0.28712303,
        0.22662454],
       [0.47605525, 0.46705041, 0.47180857, ..., 0.67511073, 0.48486071,
        0.67889035],
       [0.71040863, 0.91643517, 0.03706213, ..., 0.58032143, 0.21409719,
        0.60483283]])

In [98]:
features_test

array([[0.52200066, 0.48569984, 0.52806841, ..., 0.74311251, 0.51495632,
        0.75098482],
       [0.49793386, 0.33260912, 0.50453954, ..., 0.62602743, 0.48911282,
        0.63400011],
       [0.51546587, 0.58227963, 0.51545278, ..., 0.60953476, 0.36618314,
        0.62512698],
       ...,
       [0.50417069, 0.38834337, 0.50849248, ..., 0.664389  , 0.37370608,
        0.64905768],
       [0.64209862, 0.71073088, 0.68498938, ..., 0.45950835, 0.1800482 ,
        0.50587218],
       [0.51096761, 0.44595581, 0.51788907, ..., 0.6773274 , 0.46412081,
        0.6909293 ]])

In [99]:
labels_train

array([4, 0, 2, 0, 0, 4, 0, 4, 3, 0, 3, 0, 0, 0, 3, 3, 0, 4, 4, 0, 0, 4,
       0, 0, 2, 2, 0, 4, 2, 0, 0, 2, 0, 2, 0, 1, 2, 4, 4, 0, 2, 4, 3, 3,
       4, 1, 0, 3, 4, 4, 3, 1, 2, 3, 2, 2, 2, 0, 3, 2, 4, 3, 1, 0, 0, 2,
       1, 1, 1, 1, 3, 1, 0, 0, 1, 2, 3, 0, 4, 4, 4, 2, 2, 2, 0, 3, 4, 2,
       2, 4, 0, 0, 3, 4, 4, 1, 1, 0, 0, 3, 4, 1, 0, 0, 1, 4, 1, 0, 2, 0,
       1, 4, 4, 4, 2, 4, 2, 0, 0, 1, 2, 0, 0, 1, 0, 2, 4, 2, 3, 0, 2, 0,
       2, 1, 3, 4, 3, 0, 1, 3, 4, 4, 3, 1, 4, 0, 2, 1, 2, 0, 0, 4, 4, 0,
       2, 4, 3, 2, 1, 0, 0, 1, 4, 1, 2, 0, 0, 0, 1, 4, 4, 1, 2, 2, 4, 0,
       3, 0, 2, 0, 4, 1, 4, 2, 0, 0, 3, 2, 0, 1, 0, 2, 0, 4, 2, 2, 2, 0,
       0, 2, 3, 0, 3, 4, 1, 1, 0, 1, 0, 4, 4, 4, 1, 2, 3, 1, 1, 4, 0, 0,
       4, 0, 1, 4, 0, 2, 1, 2, 1, 0, 4, 4, 4, 1, 2, 3, 0, 0, 0, 4, 4, 3,
       4, 0, 1, 2, 2, 3, 0, 0, 1, 0, 3, 4, 0, 0, 3, 0, 1, 4, 3, 3, 4, 3,
       2, 4, 0, 4, 0, 4, 0, 0, 2, 0, 4, 4, 2, 3, 2, 1, 3, 4, 0, 0, 4, 2,
       4, 1, 0, 0, 4, 1, 2, 4, 4, 3, 3, 0, 4, 4, 2,

In [100]:
features_train.shape

(640, 34)

In [101]:
features_test.shape

(345, 34)

In [102]:
# do KNN model here and see results
from sklearn.neighbors import KNeighborsClassifier

In [103]:
classifier = KNeighborsClassifier(n_neighbors=15)

In [104]:
classifier.fit(features_train, labels_train)

KNeighborsClassifier(n_neighbors=15)

In [105]:
pred = classifier.predict(features_test)

In [106]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [107]:
# confusion matrix
print(confusion_matrix(labels_test, pred))

[[81  0  0  3  3]
 [ 0 50 12  0  1]
 [ 0  2 73  3  5]
 [ 0  2  8 16 11]
 [ 0  3 20  9 43]]


In [108]:
# classification report
print(classification_report(labels_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        87
           1       0.88      0.79      0.83        63
           2       0.65      0.88      0.74        83
           3       0.52      0.43      0.47        37
           4       0.68      0.57      0.62        75

    accuracy                           0.76       345
   macro avg       0.74      0.72      0.73       345
weighted avg       0.77      0.76      0.76       345



In [109]:
# accuracy_score
print(accuracy_score(labels_test, pred))

0.7623188405797101


In [110]:
import tensorflow as tf

In [111]:
# print(tf.__version__)

In [112]:
# see results of tensorflow model
from tensorflow.keras.layers import Input, Dense, Activation, Dropout
from tensorflow.keras.models import Model

In [113]:
# yoga_df.shape[1]

In [114]:
input_layer = Input(shape=(yoga_df.shape[1],))

In [115]:
dense_layer_1 = Dense(15, activation='relu')(input_layer)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [116]:
dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)

In [117]:
output = Dense(5, activation='softmax')(dense_layer_2)

In [118]:
model = Model(inputs=input_layer, outputs=output)

In [119]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [120]:
print(model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 34)]              0         
_________________________________________________________________
dense (Dense)                (None, 15)                525       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                160       
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 55        
Total params: 740
Trainable params: 740
Non-trainable params: 0
_________________________________________________________________
None


In [121]:
history = model.fit(features_train,labels_train, batch_size=8,epochs=50,verbose=1,validation_split=0.35)

Train on 416 samples, validate on 224 samples
Epoch 1/50
416/416 [==============================] - 0s 422us/sample - loss: 1.6064 - acc: 0.1923 - val_loss: 1.5913 - val_acc: 0.2500
Epoch 2/50
416/416 [==============================] - 0s 134us/sample - loss: 1.5558 - acc: 0.2861 - val_loss: 1.5787 - val_acc: 0.2545
Epoch 3/50
416/416 [==============================] - 0s 129us/sample - loss: 1.5380 - acc: 0.2861 - val_loss: 1.5598 - val_acc: 0.2545
Epoch 4/50
416/416 [==============================] - 0s 137us/sample - loss: 1.5003 - acc: 0.2885 - val_loss: 1.4995 - val_acc: 0.2589
Epoch 5/50
416/416 [==============================] - 0s 122us/sample - loss: 1.4387 - acc: 0.3341 - val_loss: 1.4295 - val_acc: 0.3705
Epoch 6/50
416/416 [==============================] - 0s 127us/sample - loss: 1.3727 - acc: 0.3894 - val_loss: 1.3613 - val_acc: 0.3929
Epoch 7/50
416/416 [==============================] - 0s 144us/sample - loss: 1.3153 - acc: 0.4231 - val_loss: 1.3053 - val_acc: 0.4152
Ep

In [122]:
score = model.evaluate(features_test, labels_test, verbose=1)

345/345 [==============================] - 0s 17us/sample - loss: 0.8555 - acc: 0.6377


In [123]:
print("test score: ",  score[0])

test score:  0.8554541693217512


In [124]:
print("test accuracy: ", score[1])

test accuracy:  0.6376812


In [125]:
# save model
# model.save('model.h5')